version: "3"
services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /var/tmp/docker/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - webnet

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /var/tmp/docker/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - webnet

networks:
  webnet:
volumes:
  pgdata: