version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
      PG_DATA: /var/lib/postgresql/data
    env_file:
      - docker.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  main:
    container_name: main
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - docker.env
    networks:
      - webnet
    depends_on:
      - postgres
networks:
  webnet:
volumes:
  pgdata: